<h1> Contact </h1>
<div id='divider' role="separator"></div>
<form id="form" action = ""  method="POST" role="form">
	
	<fieldset>
		<legend>Vos coordonnées</legend>

		<div class="input">
			<label for = "firstName">Prénom</label>
			<input type = "text" name = "firstName" id="firstName" required placeholder="Votre prénom ici *" value="">
			<p class="error"></p> 
		</div>

		<div class="input">
			<label for="lastName">Nom</label>
			<input type="text" name="lastName" id="lastName" required placeholder="Votre nom ici *" value="">
			<p class="error"></p>
		</div>

		<div class="input">
			<label for="email">Email</label>
			<input type="email" name="email" id="email" required placeholder="Votre mail ici *" value="">
			<p class="error"></p>
		</div>
		
		<div class="input">
			<label for="phone">Téléphone</label>
			<input type="tel" name="phone" id="phone"  maxlength="13" value="" placeholder='(+33/0) tél à 9 chiffres'>
			<p class="error"></p>
		</div>

		<label for="message">Message</label>
		<textarea placeholder="Votre message ici *"name="message" id="message" required></textarea>
		<p class="error"></p>

		<p><strong> * Ces champs sont requis</strong></p>
	</fieldset>
</form>
<fieldset id="contactSubmit">
	<legend>Envoyer</legend>
	<button type="submit" name ='' id='submitContact'>Envoyer</button>
	<button class="reset"  type="reset" name="reset">Annuler</button>
	
</fieldset>


<iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d11129.025927240786!2d4.867756137388268!3d45.78608912902522!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sdoua!5e0!3m2!1sfr!2sfr!4v1531652049306"  height="350" frameborder="0" style="border:0" allowfullscreen></iframe>












