<h1>Suppression transporteur(s)</h1>
<a href="../controller/application.php#application" class="butreward" id="butCarrierDel">Retour à l'application</a>

<form  id="carrier-del" method="POST"  accept-charset="utf-8" role="form">
	<fieldset id="fieldsetSupress">
		<legend>Suppression de transporteurs</legend>
		<?php if($collection) echo '<input type="checkbox" name="all" value="" style="width:2%;margin-right:7px;">Tout séléctionner';?>
		<ul>
			<?php 
			foreach ($collection as $value) {
				echo '<li data-checkbox="'.$value[6].'"><input type="checkbox" name="deleteCarrier" data-checkbox="'.$value[6].'" value="'.$value[1].'">'.$value[1].' et son fichier associé '.$value[6].'<a href="#"><i class="fas fa-trash" style="margin-left:1%;" title="Sélectionner pour suppression"></i></a>';
			}

			?>
		</ul>
		<input type="hidden" name="inpdelCarrier">
	</fieldset>
	<fieldset id="carrierDel-sub">
		<legend>Supprimer</legend>
		<button type="submit" id="del-carrierSubmit">Supprimer</button>
		<button type="reset">Annuler</button>
		<div class="loader"></div>
	</fieldset>
</form>
<script>
	$(function(){
		$("#carrierDel-sub").hide(300);
		$('#butconnexion').hide();
		$('ul').on('change','li[data-checkbox]>input[type=checkbox]',function(e) {
			if($(this).prop("checked")==true){
				$("#carrierDel-sub").fadeIn(300);
			}
		});
	});
</script>

