<aside>
	<h1>Présentation</h1>
	<section id="presentation">
		<p>Ce calculateur va vous aider a trouver le transporteur le moins cher
		en fonction des critères suivants : </p>
		<ul>
			<li>- Le département choisi</li>
			<li>- Le nombre d'unité de manutention remis</li>
			<li>- Le délai de livraison souhaité</li>
			<li>- Le type : palettes ou colis </li>
		</ul>
		<a href="../controller/modeEmploi.php">En savoir +</a>
	</section>

</aside> 








