<aside>
	<h1>Présentation</h1>
	<section id="presentation">Ce calculateur va vous aider a trouver le transporteur le moins cher
		en fonction : 
		<ul>
			<li>Du département choisi</li>
			<li>Du nombre d'unité de manutention remis</li>
			<li>Du délai de livraison souhaité</li>
			<li>Du type : palettes ou colis </li>
		</ul>
		<a href="../controller/modeEmploi.php">En savoir +</a>
	</section>

</aside> 








