<h2 id="start">Mode d'emploi</h2>
<nav class='navbar-modeemploi'>
	<ul>
		<li class="sous-menu"><a href="#demarrer">Pour demarrer</a></li><!--
		--><li class="sous-menu"><a href="#application">L'application</a></li><!--
		--><li class="sous-menu"><a href="#ajout">Ajouter des fichiers</a></li><!--
		--><li class="sous-menu"><a href="#supprimer">Supprimer des fichiers</a></li><!--
		--><li class="sous-menu"><a href="#userDelete">Supprimer un compte</a></li><!--
	--><li class="sous-menu"><a href="#Download">Télécharger les fichiers tests</a></li>
</ul>
</nav>
<br id="demarrer">
<hr class="modeemploi">
<br>
<section>
	<h3>Demarrer avec ce logiciel</h3>
	<p>- Ce logiciel a pour vocation de vous aider à choisir parmi la liste des transporteurs avec lesquels vous avez l'habitude de travailler.</p>
	<p>- Pour ce faire, vous devrez <b>importer les fichiers tarifaires CSV</b> respectifs en nommant chaque fichier de manière unique.<br>Il va de soi que tous doublons ou fichiers vides seront refusés. Une fois terminé vous devrez renseigner les taxes gazole respectives fournies par vos prestataires et qui peuvent varier suivant les localités et le cours du marché. </p>
	<p>- Pour l'exemple des fichiers CSV sont mis à disposition en Messagerie, Frêt, ou Affrêtement pour tester le logiciel sur les differents départements. <b><b>Ces données sont fictives</b> et ils vous appartient de compléter ces données avec vos tarifs, et d'utiliser ces fiches comme modèle pour de futurs enregistrements.</b><br>Il est important de faire concorder les fiches CSV avec le type de transport concerné.<br>Ainsi la fiche Messagerie devra être importée avec le type messagerie etc...sans quoi, les résultats obtenus risquent d'être incohérents.</p>
	<p>- Enfin vous pourrez après avoir renseigné les filtres de sélections, lancer la recherche qui s'affichera dans le bas de la "page application". Le ou les résultats concordants triés par ordre de prix seront affichés.</p>
	<p>- Vous pourrez bien entendu modifier le type du transport des fichiers associés ou le nom des fichiers eux mêmes après l'import des fichiers.Vous trouverez à cet effet un petit symbole qui vous permettra d'accéder à cette page.</p>
	<p>- La suppression d'un transporteur est également possible via le menu supérieur de l'application et en séléctionnant "Supprimer un enregistrement". Bien noter que la suppression d'un transporteur supprime aussi ses fichiers joints... pas sa modification en revanche ou là les fichiers sont conservés.</p>
	<p>- Pour terminer, vous pourrez supprimer un compte y compris si ce n'est pas le vôtre, car ce logiciel n'est qu'un exercice de présentation des acquis, et le modèle "administration" n'a pas été développé.</p>
	<p style="margin-top:200px;"></p>
</section>
<br id="application">
<hr class="modeemploi">
<br>
<section>
	<h3>L'application</h3>
	<p>- Pour se rendre à l'application elle même il faut se rendre à la page connexion:</p>
	<ul>
		<li><b><u>Vous êtes nouvel utilisateur :</u></b></li>
		<p>&nbsp;Vous êtes appelé à renseigner les champs d'inscription pour créer un compte</p>
		<p>&nbsp;Si tout se passe bien vous aurez une confirmation de validation et vous pourrez dès lors passer à la connexion.</p>
		<li><b><u>Vous êtes déjà enregistré :</u></b></li>
		<p>&nbsp;Si votre identification se passe bien via email et mot de passe, vous pourrez accéder au logiciel.</p>
	</ul>
	<p>- Une fois conecté, vous devez importer vos tarifs dans le menu : Ajouter un transporteur.</p>
	<p>- Créez autant de transporteurs que vous avez de prestataires de livraison en important à chaque fois les fiches tarifaires correspondantes.</p>
	<p>- Si tout se passe bien la barre de progression passe au vert et un bouton ajouter un nouveau transporteur apparaît.</p>
	<p>- Une fois terminé revenez a l'application par le biais du bouton retour en haut de page, vous pouvez commencer à travailler.</p>
	<p>- Vous devriez voir apparaître tous vos transporteurs en haut de page... les résultats quant à eux apparaîtrons en bas de page dans l'onglet résultat.</p>
	<p style="margin-top:200px;"></p>
</section>
<br id="ajout">
<hr class="modeemploi">
<br>
<section>
	<h3>L'ajout de fichiers</h3>
	<p>- L'ajout de fichiers tarifaires CSV se fait par le biais de l'onglet "Ajouter un transporteur" dans le menu de la page application.</p>
	<p>- Une fois sur cette page, un formulaire vous invite à renseigner le <b>nom</b> du fichier : <b>celui-ci doit être unique</b>.<br>Le logiciel n'acceptera ni deux noms identiques, ni un format different de ".CSV", ni un CSV vide.<br>Ce refus sera signalé par un message vous invitant à rectifier votre choix.</p>
	<p>-Autre information importante : <b>Le "Type" :</b></p>
	<p>&nbsp;Cette information est importante et doit correspondre à celle de la fiche tarifaire CSV, qui doit vous permettre de distinguer le mode de transport</p>
	<p>&nbsp;<b>La Messagerie :</b> qui définit un transport souvent par fourgonnette, souvent pas plus de 24H de délai de livraison et pour <b>un poids / colis inférieur ou égal a 30 kg et une limitation à 3 colis pour un même client a livrer.</b></p>
	<p>&nbsp;<b>Le Frêt :</b> qui définit un transport souvent par camion, souvent pas plus de 48H de délai de livraison et pour <b>un poids maxi souvent estimé à 500&&nbsp;kg / palette et une limitation à 5 palettes maxi pour un même client a livrer.</b><br>Suivant les prestataires ce délai de livraison peut être ramené a 24H auquel cas il vous faudra importer le tarif classique et le tarif express en donnant par exemple "Alloin" et "Alloin express" aux noms des fichiers pour ce prestataire.</p>
	<p>&nbsp; <b>L'Affrêtement :</b> qui définit un transport souvent par camion, estimé à 72H de délai de livraison et pour <b>un poids maxi souvent estimé à plus de 500 kg / palette ou à plus de 5 palettes pour un même client a livrer.</b><br>Suivant les prestataires ce délai de livraison peut être ramené a 48H auquel cas il vous faudra importer le tarif classique et le tarif express en nommant différemment chacunes des deux fiches tarifaires comme pour le Frêt.</p>
	<p>Enfin pour terminer la procédure il faudra bien entendu choisir le fichier à importer et qui est fourni dans le pack  joint à cette application.<br>A vous de compléter ces modèles d'importations pour les remplir à votre convenance.</p>
	<p style="margin-top:200px;"></p>
</section>
<br id="supprimer">
<hr class="modeemploi">
<br>
<section>
	<h3>Suppression de fiches tarifaires</h3>
	<p>- La suppression d'un fichier CSV se fait par l'onglet du menu "Supprimer un transporteur"</p>
	<p>- Une fois dans la page, la liste des transporteurs apparaît précedée de cases à cocher permettant de séléctionner les fiches souhaitées</p>
	<p>- Dès qu'une séléction est effectuée, un bouton "suppression" permet la suppression du ou des fichiers choisis après confirmation du message d'alerte.</p>
	<p>- La suppression des fichiers entraîne la suppression des importations faites précédemment, si des modifications sont à apporter, il faut préférer la modification qui permet de changer le nom, le type ou le fichier associé au nom, mais qui conserve les fichiers déjà en place.</p>
	<p style="margin-top:200px;"></p>
</section>
<br id="userDelete">
<hr class="modeemploi">
<br>
<section>
	<h3>Suppression d'un compte utilisateur</h3>
	<p>- La suppression d'un compte utilisateur se fait par l'onglet du menu "Supprimer un compte"</p>
	<p>- Cette suppression de compte implique la destruction des dossiers de stockage ainsi que les données dans la base de données.<br>Vous ne pourrez donc plus acceder à la page application tant que vous n'aurez pas recréé un nouveau compte en vous rendant sur la page de connexion.</p>
	<p>- Attention toutefois, si vous êtes connecté sur le compte que vous supprimez, vous serez naturellement redirigé sur la page d'accueil.</p>
	<p style="margin-top:200px;"></p>
</section>
<br id="Download">
<hr class="modeemploi">
<section>
	<h3>Téléchargement de fiches tarifaires pour tester le logiciel</h3>
	<h4 style="margin-left:2%;">Télécharger les fichiers suivants :</h4>
	<ul>
		<li>- <a href="..\test_messagerie24.csv">test_messagerie24.csv</a></li>
		<li>- <a href="..\test_fret24.csv">test_fret24.csv</a></li>
		<li>- <a href="..\test_fret48.csv">test_fret48.csv</a></li>
		<li>- <a href="..\test_affretement72.csv">test_affretement72.csv</a></li>
	</ul>
</section>
<p style="margin-top:200px;"></p>

