<h1>Nouveau transporteur</h1>
<a href="../controller/application.php#application" class="butreward" id="butCarrierAdd">Retour à l'application</a>
<form  id="carrier-add" method="POST" enctype="multipart/form-data" accept-charset="utf-8" role="form">
	<fieldset>
		<legend>Ajout d'un nouveau transporteur</legend>
		<label for="carrierName">Nom du transporteur</label>
		<input type="text" id="carrierName" name="nom" placeholder="Nommez votre transporteur ici *" style="background:url('../view/img/truck-solid.svg') no-repeat 7%; background-size: 5%" required >
		<p class="comment">(Si aucune saisie : "DNC" + date du jour par défaut)</p>
		<label for="carrierType">Choix du type de transporteur</label>
		<select name="type" id="carrierType" required>
			<option value="0">- Type de transport * -</option>
			<option value="1">Messagerie</option>
			<option value="2">Frêt</option>
			<option value="3">Affrètement</option>
		</select>
		<p class="comment">(Si aucune séléction : "Fret" par défaut)</p>
		<label for="carrierDataFile">Choix du fichier CSV</label>
		<input type="file" id="carrierDataFile" name="file" class="input-file" accept=".csv" value="" required >
		<input type="hidden" name="newCarrier">
		<i>Uniquement des fichiers .CSV</i>
		<p class="error"></p>
		<p><strong> * Ces champs sont requis</strong></p>
		<progress value='0' max='100' id='uploadbar'></progress>
	</fieldset>
	<fieldset>
		<legend>Envoyer</legend>
		<button type="submit" id="carrierSubmit">Envoyer</button>
		<button type="reset" onclick="var el = document.querySelector('.error'); el.innerHTML = '';var animation = document.getElementById('carrierDataFile').classList.remove('pulse');">Annuler</button>
	</fieldset>
</form>
<script>
	$(function(){
		$('#butconnexion').hide();
		$('.sandwichmenu + ul').show('300');
		$('.sandwichmenu').addClass('change');
	});
</script>
